version: "2.1"
networks:
  internal_network:
services:
#docker rm -f watchtower; docker run -it --network none --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --interval 30 --label-enable
  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower:latest
#    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #  - /root/.docker/config.json:/config.json
    command: --label-enable --cleanup --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    expose:
      - "8080"
    #ports:
    #  - "8080:8080"
    network_mode: none
#docker rm -f n2n-edge; docker run -it --privileged --network host --restart=always --log-opt max-size=1m --log-opt max-file=1 --name n2n-edge -e "CONNECT=jiayiqiu.vicp.net:30151" --label=com.centurylinklabs.watchtower.enable=true -e "IP=192.168.11.11" -e "GROUP=openwrt" land007/n2n-edge:latest
  n2n-edge:
    restart: always
    network_mode: host
    image: land007/n2n-edge:latest
#    container_name: n2n-edge
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "300k"
        max-file: "3"
    environment:
      - "CONNECT=jiayiqiu.vicp.net:30151"
      - "IP=192.168.11.11"
      - "GROUP=openwrt"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  #ubuntu1:
  #  restart: always
  #  networks:
  #    - internal_network
  #  image: land007/ubuntu:latest
  #  command: bash -c "ping www.ce.cn"
  #  privileged: true
  #ubuntu2:
  #  restart: always
  #  networks:
  #    - internal_network
  #  image: land007/ubuntu:latest
  #  command: bash -c "ping www.ce.cn"
  #  privileged: true
  


#unset ${!DOCKER_*}
#sudo docker-compose up -d
#sudo docker-compose down
  